name: CSP LLM Heuristics Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run tests
      run: |
        pytest tests/ -v --cov=. --cov-report=xml
        
    - name: Debug failed tests
      if: ${{ failure() }}
      run: |
        echo "Showing test failures with more detail:"
        pytest tests/ -v --no-header --tb=native --showlocals
        
    - name: Print test environment information
      if: ${{ failure() }}
      run: |
        echo "Python version:"
        python --version
        echo "Installed packages:"
        pip freeze
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
